# JSP View Resolver Configuration
# Prefix tells Spring where the JSP files are located
spring.mvc.view.prefix=/WEB-INF/jsp/
# Suffix tells Spring the file extension
spring.mvc.view.suffix=.jsp

# Server port (Optional, default is 8080)
server.port=8080
servSer.servlet.jsp.init-parameters.development=true